/r_arm_servo_server/delta_twist_cmds:
    type: geometry_msgs/TwistStamped
    vx:
        min: -1
        max: 1
        to: twist.linear.x
    vy:
        min: -1
        max: 1
        to: twist.linear.y
    vz:
        min: -1
        max: 1
        to: twist.linear.z
    wx:
        min: -1
        max: 1
        to: twist.angular.x
    wy:
        min: -1
        max: 1
        to: twist.angular.y
    wz:
        min: -1
        max: 1
        to: twist.angular.z
    header.frame_id: torso_lift_link